# Use node
FROM node:10
MAINTAINER Simon Fakir "simon@fakir-it.de"

# Set environment

# Copy source code
COPY . /app

# Change working directory
WORKDIR /app

#Install ffmpeg for track uploading
RUN apt-get update
RUN apt-get install ffmpeg -y

# Install dependencies
RUN npm install

# Migrate database (moved to post-run entrypoint)
# RUN npm run migrate:up

# Expose API port to the outside
EXPOSE 7001

# Launch application
CMD npm start

